name: 'SimpleLocalize'
description: 'Translation Management for software projects'
inputs:
  command:
    description: 'Command to run'
    required: true
    default: 'sync'
  apiKey:
    description: 'API Key for the project'
    required: true
    default: ''
  languageKey:
    description: 'Language key'
    required: false
    default: 'en'
  uploadPath:
    description: 'Which files should be uploaded'
    required: false
    default: './messages.json'
  uploadFormat:
    description: 'In which format do you upload the files'
    required: false
    default: 'multi-language-json'
  downloadPath:
    description: 'Which files should be downloaded'
    required: false
    default: './messages.json'
  downloadFormat:
    description: 'In which format do you want to download the files'
    required: false
    default: 'multi-language-json'
  projectType:
    description: 'i18n library'
    required: false
    default: 'react-intl'
  searchDir:
    description: 'Where CLI should look for files'
    required: false
    default: './'
runs:
  using: "composite"
  steps:
    - id: Setup
      run: curl -s https://get.simplelocalize.io/install | bash
      shell: bash
    - id: Execution
      shell: bash
      run: |
        if [ ${{ inputs.command }} = "upload" ]; then
           simplelocalize upload --apiKey ${{ inputs.apiKey }} --uploadPath ${{ inputs.uploadPath }} --uploadFormat ${{ inputs.uploadFormat }}
        fi

        if [ ${{ inputs.command }} = "download" ]; then
           simplelocalize download --apiKey ${{ inputs.apiKey }} --downloadPath ${{ inputs.downloadPath }} --downloadFormat ${{ inputs.downloadFormat }}
        fi
