name: 'SimpleLocalize Upload'
description: 'Upload i18n files to the SimpleLocalize translation management platform.'
author: "SimpleLocalize"
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  apiKey:
    description: 'API Key for the project'
    required: true
    default: ''
  languageKey:
    description: 'Language key'
    required: false
    default: 'en'
  uploadPath:
    description: 'Which files should be uploaded'
    required: false
    default: './messages.json'
  uploadFormat:
    description: 'In which format do you upload the files'
    required: false
    default: 'multi-language-json'
runs:
  using: "composite"
  steps:
    - id: Setup
      run: curl -s https://get.simplelocalize.io/install | bash
      shell: bash
    - id: Execution
      shell: bash
      run: simplelocalize upload --apiKey ${{ inputs.apiKey }} --uploadPath ${{ inputs.uploadPath }} --uploadFormat ${{ inputs.uploadFormat }}
