name: 'Pull resources from Translation Hosting'
description: 'Pull resources from Translation Hosting'
author: "SimpleLocalize"
branding:
  icon: 'download-cloud'
  color: 'blue'
inputs:
  apiKey:
    description: 'Project API Key'
    required: true
    default: ''
  pullPath:
    description: 'Choose a download location'
    required: false
    default: './hosting'
  environment:
    description: 'Choose an environment'
    required: false
    default: 'latest'
runs:
  using: "composite"
  steps:
    - id: Setup
      run: curl -s https://get.simplelocalize.io/2.1/install | bash
      shell: bash
    - id: Execution
      shell: bash
      run: simplelocalize pull --apiKey ${{ inputs.apiKey }} --pullPath ${{ inputs.pullPath }} --environment ${{ inputs.environment }}
